### PR TITLE
Improve study of Checkstyle usage in the wild

### PR DESCRIPTION
**Pull request by fermadeiral**
This PR intends to improve the study we have performed on the Checkstyle usage in the wild. For that, two major things should be done: 1) the script for the data collection must be improved, and 2) the data collection should be done again.

### CODE REVIEW

**Comment by fermadeiral** [comment]
@bloriot97, this PR is finally ready for review.

**Comment by monperrus** [comment]
162704 changed files? why so many?

**Comment by monperrus** [comment]
@fermadeiral update stale PR and then merge?

**Comment by fermadeiral** [comment]
The content of this PR was updated and pushed to https://github.com/KTH/styler/tree/checkstyle_usage_analysis, therefore this PR can be just closed.

**Pull request closed without merging**
